name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  container-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
      - name: deps
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake pkg-config
          git clone --depth 1 https://github.com/devkitPro/pacman-packages /tmp/dkp-pacman-pkgs
          cp -f /tmp/dkp-pacman-pkgs/dkp-toolchain-vars/*.sh $DEVKITPRO/.
          rm -rf /tmp/dkp-pacman-pkgs
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        run: |
          ./build.sh
      - name: store
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
